/**
 * B7.3 — a year of the engine, asserted and drawn.
 *
 * The simulated lifter lives in `tests/simulation/lifter.ts`; the drawing in
 * `tests/simulation/chart.ts`. This file is the part that matters: what the
 * year is allowed to look like.
 *
 * Four claims, from the build plan:
 *
 *   1. deloads fire,
 *   2. each cycle's peak exceeds the previous cycle's peak,
 *   3. the final weight beats the starting weight,
 *   4. the series can be charted.
 *
 * The rest of the assertions here are the ones a year-long run can make and a
 * unit test cannot: that nothing in 355 sessions violates the rules the small
 * tests check one at a time.
 *
 * Running the suite rewrites `output/simulation.svg`. That is deliberate — the
 * chart in the README is generated by the same run that proves it, so it can
 * never quietly go stale. If the engine changes shape, the diff shows up in
 * `git status`.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import { chartSeries, personalBest, streak } from "../src/engine";
import type { ChartPoint } from "../src/engine";
import { renderSimulationSvg } from "./simulation/chart";
import type { ChartPanel } from "./simulation/chart";
import { dayIndexOf, simulate } from "./simulation/lifter";

/** One run, shared by every test. The simulation is deterministic. */
const run = simulate();

/** The chart points for one lift, oldest first — the sawtooth itself. */
function seriesFor(exerciseId: string): readonly ChartPoint[] {
  return chartSeries(exerciseId, run.sessions, run.sets);
}

/**
 * One tooth of the sawtooth: the run of sessions between two drops.
 *
 * Split on `weightDropped` rather than on the deload records, so the cycles
 * are read off the chart the way a person reads it. That the two agree is
 * itself a test, below.
 */
function cycles(points: readonly ChartPoint[]): ChartPoint[][] {
  const out: ChartPoint[][] = [];
  let current: ChartPoint[] = [];
  for (const point of points) {
    if (point.weightDropped && current.length > 0) {
      out.push(current);
      current = [];
    }
    current.push(point);
  }
  if (current.length > 0) out.push(current);
  return out;
}

/**
 * The teeth that finished.
 *
 * The last run of sessions in the year ends because the year ended, not
 * because the engine backed off — its top is wherever the calendar stopped
 * rather than a peak, and comparing it against a real peak would be comparing
 * a tooth with the stump of one.
 */
function completeCycles(points: readonly ChartPoint[]): ChartPoint[][] {
  return cycles(points).slice(0, -1);
}

/** The heaviest weight attempted in a tooth. */
function peak(cycle: readonly ChartPoint[]): number {
  return Math.max(...cycle.map((p) => p.weightKg));
}

const lifts = run.lifts.map((lift) => ({
  ...lift,
  points: seriesFor(lift.exercise.id),
  deloads: run.deloads.filter((d) => d.exerciseId === lift.exercise.id),
}));

/** `describe.each` wants a label first. */
const perLift = lifts.map((lift) => [lift.exercise.name, lift] as const);

/* ---------------------------------------------------------- the year ran */

describe("a simulated year", () => {
  it("trains every day except the holiday", () => {
    // 365 days, ten of them off. No catch-up sessions were invented to make
    // up for them, and none should have been (INV-6).
    expect(run.sessions).toHaveLength(355);
  });

  it("keeps the rotation on its position, not on the calendar (INV-6)", () => {
    // Ten days missed is two full turns of a five-lift rotation, so a calendar
    // rule would land on the same lifts afterwards and this test would pass by
    // accident. The order is checked session by session instead.
    const order = run.lifts.map((lift) => lift.exercise.id);
    run.sessions.forEach((session, index) => {
      expect(session.exerciseId).toBe(order[index % order.length]);
    });
  });

  it("gives every lift the same number of sessions", () => {
    for (const lift of lifts) {
      const all = run.sessions.filter((s) => s.exerciseId === lift.exercise.id);
      expect(all).toHaveLength(71);
    }
  });
});

/* ------------------------------------------------------- the four claims */

describe.each(perLift)("%s", (_name, lift) => {
  it("deloads at least once", () => {
    expect(lift.deloads.length).toBeGreaterThan(0);
  });

  it("ends the year heavier than it started", () => {
    const first = lift.points[0]!;
    const last = lift.points[lift.points.length - 1]!;
    expect(last.weightKg).toBeGreaterThan(first.weightKg);
    expect(first.weightKg).toBe(lift.exercise.startKg);
  });

  it("makes each tooth taller than the one before it", () => {
    // The claim the whole simulation exists to check: backing off is not
    // losing ground. Every cycle tops out above the last one's top.
    const peaks = completeCycles(lift.points).map(peak);
    expect(peaks.length).toBeGreaterThan(2);
    for (let i = 1; i < peaks.length; i += 1) {
      expect(peaks[i]!).toBeGreaterThan(peaks[i - 1]!);
    }
  });

  it("only ever loses weight to a deload", () => {
    // The simulated lifter never edits a weight by hand, so a drop on the
    // chart has exactly one possible cause. This is what makes the chart
    // readable: every notch is the engine backing off after three stalls.
    const drops = lift.points.filter((p) => p.weightDropped).map((p) => p.trainingDay);
    // The notch trails the deload by one session. The engine decides on the
    // third stalled session, but the lighter weight is what it prescribes
    // *next* — five days later, when the lift comes round again. A deload on
    // the last session of the year therefore never reaches the chart at all.
    const expected = lift.deloads
      .map((deload) => lift.points.find((p) => p.trainingDay > deload.trainingDay))
      .filter((point): point is ChartPoint => point !== undefined)
      .map((point) => point.trainingDay);
    expect(drops).toEqual(expected);
  });

  it("never lowers the weight inside a cycle (B7.2.3)", () => {
    for (const cycle of cycles(lift.points)) {
      for (let i = 1; i < cycle.length; i += 1) {
        expect(cycle[i]!.weightKg).toBeGreaterThanOrEqual(cycle[i - 1]!.weightKg);
      }
    }
  });

  it("moves in whole steps, with no drift after a year (B7.2.4)", () => {
    // 71 sessions of repeated addition is where floating point would show up
    // if `roundKg` were not doing its job: every weight is a whole number of
    // steps away from where the lift started.
    const step = run.equipment.stepKg;
    for (const point of lift.points) {
      const steps = (point.weightKg - lift.exercise.startKg) / step;
      expect(Math.abs(steps - Math.round(steps))).toBeLessThan(1e-9);
    }
  });

  it("reports the personal best as the heaviest weight completed (B6.4)", () => {
    const best = personalBest(lift.exercise.id, run.sessions);
    expect(best).not.toBeNull();
    expect(best!.weightKg).toBe(Math.max(...lift.points.map((p) => p.weightKg)));
  });
});

/* ------------------------------------------------ what a year adds to B5 */

describe("the interruptions cost nothing", () => {
  const abandoned = run.sessions.find((s) => s.status === "abandoned")!;

  it("has one abandoned session", () => {
    expect(abandoned).toBeDefined();
    expect(abandoned.finishedAt).toBeNull();
  });

  it("repeats the same weight afterwards, with no stall counted (B5.7)", () => {
    const sameLift = run.sessions.filter((s) => s.exerciseId === abandoned.exerciseId);
    const next = sameLift[sameLift.indexOf(abandoned) + 1]!;
    expect(next.prescribedKg).toBe(abandoned.prescribedKg);
  });

  it("keeps the abandoned session out of the chart (B6.1)", () => {
    const points = seriesFor(abandoned.exerciseId);
    expect(points.map((p) => p.sessionId)).not.toContain(abandoned.id);
  });

  it("counts the streak from the last completed session (B6.3)", () => {
    // The holiday and the walked-away-from session both break the streak, and
    // neither leaves a debt behind: the count simply starts again.
    const abandonedDay = dayIndexOf(abandoned.trainingDay);
    expect(streak(run.sessions, run.lastDay)).toBe(run.days - 1 - abandonedDay);
  });
});

/* ------------------------------------------------------------ the artefact */

const OUTPUT_DIR = join(process.cwd(), "output");

describe("the chart", () => {
  const panels: ChartPanel[] = lifts.map((lift) => ({
    name: lift.exercise.name,
    points: lift.points.map((p) => ({
      day: dayIndexOf(p.trainingDay),
      weightKg: p.weightKg,
    })),
    deloadDays: lift.points
      .filter((p) => p.weightDropped)
      .map((p) => dayIndexOf(p.trainingDay)),
    capacityKg: lift.capacityKg,
  }));

  it("has a recognisable sawtooth in it", () => {
    // What "recognisable" means, stated as numbers rather than left to the
    // eye: several teeth per lift, and a rise from first to last that is worth
    // drawing at all.
    for (const lift of lifts) {
      expect(completeCycles(lift.points).length).toBeGreaterThanOrEqual(3);
      const first = lift.points[0]!.weightKg;
      const last = lift.points[lift.points.length - 1]!.weightKg;
      expect(last - first).toBeGreaterThan(run.equipment.stepKg * 5);
    }
  });

  it("writes output/simulation.json and output/simulation.svg", () => {
    const series = {
      about:
        "Generated by tests/simulation.test.ts (B7.3). A virtual lifter run through src/engine/, unmodified.",
      firstDay: run.firstDay,
      lastDay: run.lastDay,
      days: run.days,
      stepKg: run.equipment.stepKg,
      sessions: run.sessions.length,
      lifts: lifts.map((lift) => ({
        id: lift.exercise.id,
        name: lift.exercise.name,
        startKg: lift.exercise.startKg,
        endKg: lift.points[lift.points.length - 1]!.weightKg,
        deloads: lift.deloads.length,
        points: lift.points.map((p) => ({
          day: dayIndexOf(p.trainingDay),
          trainingDay: p.trainingDay,
          weightKg: p.weightKg,
          estimated1RM: p.estimated1RM,
          weightDropped: p.weightDropped,
          personalBest: p.personalBest,
        })),
        capacityKg: lift.capacityKg.map((kg) => Number(kg.toFixed(2))),
      })),
    };

    const svg = renderSimulationSvg(panels, {
      days: run.days,
      stepKg: run.equipment.stepKg,
      sessions: run.sessions.length,
    });

    mkdirSync(OUTPUT_DIR, { recursive: true });
    writeFileSync(join(OUTPUT_DIR, "simulation.json"), `${JSON.stringify(series, null, 2)}\n`);
    writeFileSync(join(OUTPUT_DIR, "simulation.svg"), svg);

    expect(svg.startsWith("<svg")).toBe(true);
    for (const lift of lifts) expect(svg).toContain(lift.exercise.name);
  });
});
